//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgsPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NgsPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Processing has been interrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbortedText {
            get {
                return ResourceManager.GetString("AbortedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Browse... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrowseButton_Text {
            get {
                return ResourceManager.GetString("BrowseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelledText {
            get {
                return ResourceManager.GetString("CancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Checksum File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChecksumFile {
            get {
                return ResourceManager.GetString("ChecksumFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    To activate the mod, a separate third-party launcher and checksum file are required. Overwrite this file in data\win32. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChecksumFileInformationText {
            get {
                return ResourceManager.GetString("ChecksumFileInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompleteText {
            get {
                return ResourceManager.GetString("CompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompressCheckboxText {
            get {
                return ResourceManager.GetString("CompressCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crypt (not recommended) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CryptCheckBoxText {
            get {
                return ResourceManager.GetString("CryptCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorTitleText {
            get {
                return ResourceManager.GetString("ErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outputs a list of game data files in the target directory in CSV format. Read it into Excel etc. and extract the necessary files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportFileListInformationText {
            get {
                return ResourceManager.GetString("ExportFileListInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export File List to csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportFileListText {
            get {
                return ResourceManager.GetString("ExportFileListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSO2 Data File (*.ice)|*.ice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IceFileFilterText {
            get {
                return ResourceManager.GetString("IceFileFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language_Content {
            get {
                return ResourceManager.GetString("Language_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Threads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxThreads_Header {
            get {
                return ResourceManager.GetString("MaxThreads_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the maximum number of threads for parallel processing. The higher the number, the faster the processing ends, but it also consumes a large amount of memory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxThreads_Tooltip {
            get {
                return ResourceManager.GetString("MaxThreads_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The act of modifying game data (modding) does not infringe on the right to maintain integrity, and is within the scope of the freedom of expression stipulated in Article 21 of the Japanese Constitution and the Fair Use law stipulated in Article 107 of the U.S. Copyright Act.
        ///
        ///However, please keep in mind that modding is potentially damaging to the game environment and may result in a ban.
        ///In particular, the dissemination of private internal data in a community that can be viewed by an unspecified number  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModdingWarningText {
            get {
                return ResourceManager.GetString("ModdingWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some files are not completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotCompletedText {
            get {
                return ResourceManager.GetString("NotCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify when completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyComplete_Header {
            get {
                return ResourceManager.GetString("NotifyComplete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A desktop notification is issued when the process is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyComplete_ToolTip {
            get {
                return ResourceManager.GetString("NotifyComplete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the directory that contains the files you want to pack. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackDialogText {
            get {
                return ResourceManager.GetString("PackDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To create a PSO2 mod, click &quot;Pack&quot; and select a directory. You can create a mod by creating modified data with the same structure as an existing file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackInformationText {
            get {
                return ResourceManager.GetString("PackInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Packing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackingText {
            get {
                return ResourceManager.GetString("PackingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the folder that contains the files you want to pack. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackInputPathText {
            get {
                return ResourceManager.GetString("PackInputPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackText {
            get {
                return ResourceManager.GetString("PackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressFileListCaption {
            get {
                return ResourceManager.GetString("ProgressFileListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Generating file list. ({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressFileListMessage {
            get {
                return ResourceManager.GetString("ProgressFileListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressInitializeCaption {
            get {
                return ResourceManager.GetString("ProgressInitializeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now acquiring the file list of the target directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressInitializeMessage {
            get {
                return ResourceManager.GetString("ProgressInitializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Packing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressPackCaption {
            get {
                return ResourceManager.GetString("ProgressPackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting files to include in {2}. ({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressPackMessage {
            get {
                return ResourceManager.GetString("ProgressPackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpacking... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressUnpackCaption {
            get {
                return ResourceManager.GetString("ProgressUnpackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting contents of {2}. ({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressUnpackMessage {
            get {
                return ResourceManager.GetString("ProgressUnpackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path of pso2_bin Path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pso2BinPathLabel_Content {
            get {
                return ResourceManager.GetString("Pso2BinPathLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pso2.exe was not installed or was not found.
        ///Please select the correct directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pso2ExeNotFoundErrorText {
            get {
                return ResourceManager.GetString("Pso2ExeNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the save destination. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAsDialogText {
            get {
                return ResourceManager.GetString("SaveAsDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveButton_Text {
            get {
                return ResourceManager.GetString("SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All rights to the copyrighted works (images, data, audios, texts, etc.) used in &quot;PSO2: NGS&quot; are owned by SEGA Corporation or its licensors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SegaCopyrightNotice {
            get {
                return ResourceManager.GetString("SegaCopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regarding Copyright Infringement and Illicit Activities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SegaCopyrightWarningLinkText {
            get {
                return ResourceManager.GetString("SegaCopyrightWarningLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://pso2.com/players/news/780/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SegaCopyrightWarningLinkUrl {
            get {
                return ResourceManager.GetString("SegaCopyrightWarningLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the pso2_bin directory (the directory where pso2.exe resides). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectPso2BinPathText {
            get {
                return ResourceManager.GetString("SelectPso2BinPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate output directories by group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateByGroupCheckBoxText {
            get {
                return ResourceManager.GetString("SeparateByGroupCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSO2 data files are divided into two groups according to extension and file name. If you check this checkbox, subdirectories &quot;group1&quot; and &quot;group2&quot; will be created at the time of unpacking and sorted according to the file affiliation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateByGroupCheckBoxToolTip {
            get {
                return ResourceManager.GetString("SeparateByGroupCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings have been saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSavedText {
            get {
                return ResourceManager.GetString("SettingsSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetDirectoryItemAll {
            get {
                return ResourceManager.GetString("TargetDirectoryItemAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSO2NGS Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetDirectoryItemNgs {
            get {
                return ResourceManager.GetString("TargetDirectoryItemNgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSO2 Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetDirectoryItemPso2 {
            get {
                return ResourceManager.GetString("TargetDirectoryItemPso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Directory: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetDirectoryText {
            get {
                return ResourceManager.GetString("TargetDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleTheme_Header {
            get {
                return ResourceManager.GetString("ToggleTheme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle dark theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleTheme_Tooltip {
            get {
                return ResourceManager.GetString("ToggleTheme_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traverses PSO2&apos;s data directory, storing file hashes and contents as a cache in a SQLite database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolsGenerateCacheInformation {
            get {
                return ResourceManager.GetString("ToolsGenerateCacheInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolsText {
            get {
                return ResourceManager.GetString("ToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the list file that contains the list of files you want to unpack. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackByFileListDialogText {
            get {
                return ResourceManager.GetString("UnpackByFileListDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack all at once from the file list.
        ///The file list format is a list of file names from the data directory separated by newlines. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackByFilelistInformationText {
            get {
                return ResourceManager.GetString("UnpackByFilelistInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack from file list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackByFileListText {
            get {
                return ResourceManager.GetString("UnpackByFileListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the * .ice file you want to unpack. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackDialogText {
            get {
                return ResourceManager.GetString("UnpackDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To unzip the PSO2 data file, click the &quot;Unpack&quot; button, select the data file, and select the output destination directory in the next dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackInformationText {
            get {
                return ResourceManager.GetString("UnpackInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpacking... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackingText {
            get {
                return ResourceManager.GetString("UnpackingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the output destination of the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackOutputPathText {
            get {
                return ResourceManager.GetString("UnpackOutputPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackText {
            get {
                return ResourceManager.GetString("UnpackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit Project Site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VisitText {
            get {
                return ResourceManager.GetString("VisitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSO2 game data is divided into Group 1 and Group 2 by extension and file name, and packed as one. Files contained in this form are assigned to Group 1.
        ///
        ///Do not change if you are not sure. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WhiteListDescription_Text {
            get {
                return ResourceManager.GetString("WhiteListDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files to be classified into group 1 when packed (suffix match/line feed delimiter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WhiteListLabel_Content {
            get {
                return ResourceManager.GetString("WhiteListLabel_Content", resourceCulture);
            }
        }
    }
}
