//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgsPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NgsPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify when completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyCompleteText {
            get {
                return ResourceManager.GetString("NotifyCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A desktop notification is issued when the process is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyCompleteTooltip {
            get {
                return ResourceManager.GetString("NotifyCompleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackButton {
            get {
                return ResourceManager.GetString("PackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle dark theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleDarkThemeTooltip {
            get {
                return ResourceManager.GetString("ToggleDarkThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleThemeText {
            get {
                return ResourceManager.GetString("ToggleThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnpackButton {
            get {
                return ResourceManager.GetString("UnpackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit Project Site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VisitText {
            get {
                return ResourceManager.GetString("VisitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name to classify into group 1 (last match, Line break delimiter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WhiteListText {
            get {
                return ResourceManager.GetString("WhiteListText", resourceCulture);
            }
        }
    }
}
